### ISSUE TITLE
Variable length lookbehind patterns

### ISSUE THREAD

**Issue by bikky9** [boostorg/regex#170]
I am consuming boost library for regex matching. Recently we have upgraded boost from version 1.37 to 1.65 and then suddenly the regexes having patterns like (?<=^|\s|_), (?<!\d{3}|\d{4}) are failing to compile. Most of the failing regexes are having variable length lookbehind patterns

I see from documentation that lookbehind regexes should have fixed length pattern and that should be why the above regexes are failing to compile. I am wondering why they used to work in 1.37 and not now? Is there any optimization that pushed to remove variable length regex patterns?

**Comment by redactedscribe** [comment]
I'm attempting to use `(?<=^|\s)` in [Mp3tag](https://www.mp3tag.de/en/) (which [credits boost::regex](https://help.mp3tag.de/misc_credits.html)) but Mp3tag is returning "Invalid lookbehind assertion encountered in the regular expression.".

The workaround I've been using (which I believe is equivalent in result but not efficiency) is `((?<=^)|(?<=\s))`.

Testing the former expression via [regex101](https://regex101.com/)'s PCRE2 (PHP >=7.3) flavour shows that it is valid, which is why I think the issue is within Boost. Both regex101 and Mp3tag accept the latter just fine.

\- Boost 1.75.0? (this is the version of the Boost docs that Mp3tag's credits link to, but the actual version in use may differ)
\- Mp3tag 3.11

Thanks.

**Comment by jzmaddock** [comment]
We have never supported variable-length-lookbehind, but I'll keep it in mind for future enhancements.

**Comment by JohnAlt2** [comment]
Suggest CLOSE TICKET as all questions here appear to be answered.

**Comment by jzmaddock** [comment]
Agreed, it's not easy to implement, and I don't have time at present...
