### ISSUE TITLE
boost::regex_search crash

### ISSUE THREAD

**Issue by siten** [boostorg/regex#37]
Using the regular expression "<pre.*class=.+id=.+>([\\s\\S]+)</pre>" to search  crash.txt
 file, boost::regex_search function will be very slow and will crash.
[crash.txt](https://github.com/boostorg/regex/files/1185690/crash.txt)

**Comment by jzmaddock** [comment]
It doesn't crash: it throws an exception to indicate that backtracking was taking excessive time.

There is an error in your expression as well: if this is for embedding in C++ code, then the string should be: "<pre.*class=.+id=.+>([\\s\\S]+)" since C++ gobbles the first "\".  An alternative to avoid this is to use raw string literals.  If you do this then the expression behaves fine.

BTW I tried your expression (the "<pre.*class=.+id=.+>([sS]+)" variant, which is what you were actually trying, even if this wasn't what you intended) at https://regex101.com/ with pcre and "single line" mode activated (Boost Regex default), and it bombs out as well with:

_"Catastrophic backtracking has been detected and the execution of your expression has been halted. To find out more what this is, please read the following article: Runaway Regular Expressions

I recommend you launch the debugger in the menu to the left and analyze the data to find out the cause."_

**Comment by siten** [comment]
Okay, thank you.

**Comment by siten** [comment]
I'm sorry I was wrong to write the regular expression "<pre.*class=.+id=.+>([\s\S]+)" . I tested "<pre.*class=.+id=.+>([\\s\\S]+)<\\/pre>" in my C++ code  boost::regex_search still  throws an exception.
In addition, "<pre.*class=.+id=.+>([sS]+)<\\/pre>" can not match the results I want. 
Use the STL regx or python with "<pre.*class=.+id=.+>([\\s\\S]+)<\\/pre>"  i can get the results.

**Comment by siten** [comment]
I'm sorry I was wrong to write the regular expression "<pre.*class=.+id=.+>([\\s\\S]+)" . I tested "<pre.*class=.+id=.+>([\\\\s\\\\S]+)<\\\\/pre>" in my C++ code boost::regex_search still throws an exception.
In addition, "<pre.*class=.+id=.+>([sS]+)<\\\\/pre>" can not match the results I want.
Use the STL regx or python with "<pre.*class=.+id=.+>([\\\\s\\\\S]+)<\\\\/pre>" i can get the results.

**Comment by siten** [comment]
thank you.
